#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

############################################
# Install NodeBB
############################################

dir=$PWD
if [ ! -d "/opt/nodebb" ]; then

    cd /opt
    git clone -b v2.8.6 https://github.com/NodeBB/NodeBB.git nodebb
    cp /opt/nodebb/install/package.json /opt/nodebb/package.json
    cd /opt/nodebb
    npm install

fi

# Copy over our Quick Install App
cd $dir
rsync -r ./Installers/ /usr/local/hestia/web/src/app/WebApp/Installers/

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "NodeBB" "&#128153; NodeBB plugin has finished installing."