#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

############################################
# Install NodeBB
############################################

dir=$PWD
if [ ! -d "/opt/nodebb/v3.2.1" ]; then

    mkdir -p /opt/nodebb/v3.2.1
    cd /opt/nodebb/v3.2.1
    git clone -b v3.2.1 https://github.com/NodeBB/NodeBB.git nodebb
    cd nodebb
    rm -rf .git
    rm -rf .gitignore
    rm -rf .DS_Store
    ./nodebb setup --help
fi

# Copy over our Quick Install App
cd $dir
rsync -r ./Installers/ /usr/local/hestia/web/src/app/WebApp/Installers/

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "NodeBB" "&#128153; NodeBB plugin has finished installing."